### ISSUE TITLE
Conversion of smart quotes?

### ISSUE THREAD

**Issue by robinmalik** [SamuelCharpentier/remove-non-ascii-chars#3]
Hi,

Thanks for this extension :) Would it be possible for this extension to convert smart quotes and hyphens automatically also? Certainly for the former, it'd avoid the case whereby smart quotes are removed but not replaced with anything, and then it breaks your code.

This is a useful page for grabbing the characters themselves: https://smartquotesforsmartpeople.com/

Perhaps it'd make sense to include smart apostrophes too?

**Comment by SamuelCharpentier** [comment]
Hi Robin,

I think this would make more sense in a separate extension as the smart quotes character is actually not part of the ascii printable characters (ignoring the extended set). As the name imply, this extension if specifically to ensure the characters are part of that set.

As this was my first VS Code extension, I feel like anybody with basic understanding of Javascript should be able to replicate, especially since you've found the source code.

Use my source code if you'd like a short cut to create your own. This was a great way to learn more about my IDE.

Good luck!
